export const SPECIALIZATIONS = [
  // Core Development
  "Web Developer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Software Engineer",

  // Mobile & Platform
  "Mobile App Developer",
  "Android Developer",
  "iOS Developer",
  "Cross Platform Developer",

  // Data & AI
  "Data Scientist",
  "Data Analyst",
  "Machine Learning Engineer",
  "AI Engineer",
  "Deep Learning Engineer",
  "NLP Engineer",
  "Computer Vision Engineer",

  // Cloud & DevOps
  "DevOps Engineer",
  "Cloud Engineer",
  "Site Reliability Engineer (SRE)",
  "Platform Engineer",
  "Infrastructure Engineer",

  // UI/UX & Design
  "UI Developer",
  "UX Designer",
  "Product Designer",
] as const;

export const SKILLS = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Vue",
  "Angular",
  "Node.js",
  "Express",
  "Django",
  "Flask",
  "Spring Boot",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "AWS",
  "Azure",
  "Google Cloud",
  "Terraform",
  "Python",
  "Java",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Flutter",
  "React Native",
  "Kotlin",
  "Swift",
  "Machine Learning",
  "Deep Learning",
  "TensorFlow",
  "PyTorch",
  "Pandas",
  "NumPy",
  "Git",
  "Linux",
  "REST API",
  "GraphQL",
  "Microservices",
  "System Design",
  "Data Structures",
  "Algorithms",
];
