import "./globals.css";
import { Toaster } from "sonner";
import type { Metadata } from "next";
import { cn } from "@/src/shared/utils/utils";
import Providers from "@/src/shared/components/Providers";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Navbar from "@/src/shared/components/Navbar";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
        "dark",
      )}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <div className="min-w-full h-screen flex flex-col">
            <Navbar />
            <div className="min-w-full flex flex-1 overflow-hidden">
              <main className="flex-1 overflow-auto">{children}</main>
              <Toaster richColors position="top-right" />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
